---
title: "Reopt"
author: "Grace Bianchi"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(RJSONIO)
library(jsonlite)
```

### Obtain MSA zip code information
```{r}
token <- "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNmMmU0Yzg1ZWZlMDNiYTkxNTA4YzdlNWJiYjE1NjVkNzIyNjg4MzgwYTE4OWNjNmJkOWRjNjFiZWUyZjIwYzg0ZmJjNmZkOTc0MDg4YzRmIn0.eyJhdWQiOiI2IiwianRpIjoiY2YyZTRjODVlZmUwM2JhOTE1MDhjN2U1YmJiMTU2NWQ3MjI2ODgzODBhMTg5Y2M2YmQ5ZGM2MWJlZTJmMjBjODRmYmM2ZmQ5NzQwODhjNGYiLCJpYXQiOjE2ODI0ODQyOTYsIm5iZiI6MTY4MjQ4NDI5NiwiZXhwIjoxOTk4MTAzNDk2LCJzdWIiOiI0ODUyMyIsInNjb3BlcyI6W119.G7NL2Khpo602p_fzk6EiAZ0-KdXsVW-IO9mUqwHem0YFLaTQZezotmLqXmbcTi7BxRzc8UHNYBw415CCzKo81w"

# cbsa-ziip data
cbsa_url <- "https://www.huduser.gov/hudapi/public/usps?type=8&query=All"

# zip-cbsa : type3
zip_url <- "https://www.huduser.gov/hudapi/public/usps?type=3&query=All"

# set the authorization header
headers <- add_headers("Authorization" = paste("Bearer", token))

# Send the GET request to retrieve the results
cbsa_response <- GET(url = cbsa_url,add_headers("Authorization" = paste("Bearer", token)))

# Extract the response content as JSON and convert it to a list
response_content <- content(cbsa_response, as="text")
response_cbsa <- fromJSON(response_content)

# make data frame
cbsa_city_data <- data.frame("geoid"= response_cbsa$data$results$geoid,
                             "cbsa"= response_cbsa$data$results$cbsa,
                            "city"= response_cbsa$data$results$city)

zip_response <- GET(url = zip_url ,add_headers("Authorization" = paste("Bearer", token)))
# Extract the response content as JSON and convert it to a list
response_zip_content <- content(zip_response, as="text")
response_list <- fromJSON(response_zip_content)


zip_data <- data.frame("geoid"= response_list$data$results$geoid,
                            "zipcode"= response_list$data$results$zip,
                             "state"= response_list$data$results$state)
# combine data sets
zip_cbsa_data <- cbsa_city_data %>% 
  right_join(zip_data)
  
```

```{r polulation estimates}
api_key <- "ebab921b3002df9b71881ad6c426f34281ce0e11"
# Add key to .Renviron
Sys.setenv(CENSUS_KEY="ebab921b3002df9b71881ad6c426f34281ce0e11")
# Reload .Renviron
readRenviron("~/.Renviron")
# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")

host <- "https://api.census.gov/data"
year <- "2021"
pop_est_stem <- "pep/population"

job_end <- "acs/acs1?get=NAME,B01001_001E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key="

version_url <- file.path(host, year, job_end)
pop_list <- fromJSON(version_url) %>% # retrieved cbsa numbers, msa names, and some value??
  row_to_names(1) %>% clean_names() %>% 
  as.data.frame() %>% 
  rename("msa"= name,
                             "cbsa" = metropolitan_statistical_area_micropolitan_statistical_area,
                             "pop_esta"= b01001_001e)

msa_zip_pop_est_data <- pop_list %>% 
  left_join(cbsa_city_data) %>% 
  inner_join(zip_data)


```

# reopt inputs
```{r}
# create list of default inputs for each city
inputs <- list(
  offtaker_tax_pct = 0, # host effective tax rate
  co2_cost_us_dollars_per_tonne = 185,
  module_type = 1,
  dc_ac_ratio = 1.35,
  losses = 0.05,
  federal_itc_pct = 0.3,
  location = "roof", # restrict projects to roof
  can_net_meter = TRUE
  
)
```

# Set the payload for the job submission request for reopt
```{r}
# Set the payload for the job submission request
payload <- list(
  "Scenario" = list(
    "Site" = list(
      "longitude" = -118.1164613,
      "latitude" = 34.5794343,
      "roof_squarefeet" = 5000.0,
      "PV" = list(
        "installed_cost_us_dollars_per_kw" = 2000.0,
        "federal_rebate_us_dollars_per_kw" = 350.0,
        # changes from default
        "module_type" = 1,
        "dc_ac_ratio" = 1.35, # changed default
        "losses" = 0.05,   # changed default
        "federal_itc_pct" = 0.3,  # changed default
        "location" = "roof", # restrict projects to roof
        "can_net_meter" = TRUE
      ),
      "LoadProfile" = list(
        "doe_reference_name" = "MidriseApartment",
        "annual_kwh" = 10000000.0,
        "city" = "LosAngeles"
      ),
      "ElectricTariff" = list(
        "urdb_label" = "5ed6c1a15457a3367add15ae",
        "add_tou_energy_rates_to_urdb_rate" = TRUE
      ),
      "Financial" = list(
        "escalation_pct" = 0.026,
        "offtaker_discount_pct" = 0.081,
        "owner_discount_pct" = 0.081,
        "analysis_years" = 20,
        "offtaker_tax_pct" = 0.4,
        "owner_tax_pct" = 0.4,
        "om_cost_escalation_pct" = 0.025
      )
    )
  )
)


```


## OpenEI 
```{r}
## open EI api
openEI_api_key <- "rU6MEqhK9OJ7obAnmcbzYhpFOenfBM5Q8GF0yJFA"

openEI_start <- "https://api.openei.org/utility_rates?version=latest&format=json&sector=Residential&detail=full&approved=true&sort_select=effectiveDate&direction=desc&"
# Set the URL for the job submission endpoint


openEI_url <- paste0(openEI_start, "address=", "46033", "&api_key=", openEI_api_key)
EIresponse <- GET(openEI_url)
# extract contents
content <- content(EIresponse, "text")
utility_data <- fromJSON(content)

 # extract utility rate information
EIutility_df <- list(
  start_date = utility_data$items$startdate,
  #revisions = utility_data$items$revisions,
  label = utility_data$items$label,
  utility = utility_data$items$utility,
  rate_name = utility_data$items$name)

startdates <- EIutility_df$start_date
start_dates_rev <- lapply(startdates, function(x) as.Date(x/86400, origin="1970-01-01"))


```


```{r}
## function to select the most recent utiilty rate information for a given area code
get_zip_utility <- function(zipcode){
  openEI_start_url <- "https://api.openei.org/utility_rates?version=latest&format=json&sector=Residential&detail=full&approved=true&address="
openEI_api_end <- "&api_key=rU6MEqhK9OJ7obAnmcbzYhpFOenfBM5Q8GF0yJFA"
zipcode=zipcode

  openEI_url <- paste0(openEI_start_url, zipcode, openEI_api_end)
  response <- GET(openEI_url)
  # extract content and parse as JSON
  content <- content(EIresponse, "text")
  json <- fromJSON(content)
  
  utility_df <- data.frame(
  # repeat zipcode in each row for each utility observation
  "zipcode" = rep(zipcode, each=nrow(json$items$label)),
  "start_date" = utility_data$items$startdate,
  "label" = json$items$label,
    "utility" = json$items$utility,
    "rate_name" = json$items$name) 
  
  # Find index of row with most recent start date value
  max_index <- which.max(utility_df$start_date) 

# Extract row with greatest seconds value
  max_row <- utility_df[max_index, ]
  

}

test <- get_zip_utility(46033) %>% 
     mutate(start_date = as.Date(start_date/86400, origin="1970-01-01"))

```

```{r}
# Define a vector of zip codes
zipcodes <- c("90210", "10001", "60601", "90245", "90001", "90250", "90260", "90278", "90501", "90502")

# Initialize an empty list to store the results
utility_list <- list()

# Loop through each zip code and call the get_zip_utility function
for (zipcode in zipcodes) {
  utility_data <- get_zip_utility(zipcode)
  utility_list[[zipcode]] <- utility_data
}

# Combine the results into a single data frame
utility_df <- do.call(rbind, utility_list)

```



```{r STUFF TO WORK ON}

net_metering_limit_kw # by state
```

### Reopt API

```{r}
# Set your API key
api_key <- "GZtZAUcX97VchjrLAeeN3amg2pslaO3hbtCQgXBl"

# Set the URL for the job submission endpoint
url <- "https://developer.nrel.gov/api/reopt/stable/job"

job_url <- paste0(url, "?api_key=", api_key)
```

```{r}
# Make the request to submit the job
response <- POST(url, query = list(api_key = api_key), body = payload, encode = "json", timeout(30))

# Check the response status code
status_code <- response$status_code
if (status_code == 200) {
  message("Inputs updated successfully.")
} else {
  message("Error updating inputs.")
}

# get run_uuid to obtain outputs
output <- httr::content(response)
run_uuid <- output$run_uuid
```

 
```{r}
## GET RESULTS FROM REOPT
results_url <- paste0("https://developer.nrel.gov/api/reopt/stable/job/", run_uuid, "/results")

# Send the GET request to retrieve the results
response <- GET(url = results_url, query = list(api_key = api_key), timeout(30))

# Extract the response content as JSON and convert it to a list
response_content <- content(response, as="text")
response_json <- fromJSON(response_content)

# pull out IMPORTANT data
output_df <- data.frame(
  IRR = response_json$outputs$Scenario$Site$Financial$irr_pct,
  Health_Emissions_Cost = response_json$outputs$Scenario$Site$lifecycle_emissions_cost_Health_bau,
  Annual_Generation_Renewables = response_json$outputs$Scenario$Site$annual_renewable_electricity_pct)

```
 
```{r}
host <- "https://developer.nrel.gov/api/reopt"
api_key <- "?API_KEY=GZtZAUcX97VchjrLAeeN3amg2pslaO3hbtCQgXBl"
version_url <- file.path(host, help_end, api)
api_version <- jsonlite::fromJSON(version_url) # retrieved 

```


```{r}
#PV & wind space available:  ❌ Land only ✅ Roofspace only ❌ Land & roofspace

#PV System Characteristics
ModuleType= Premium
DCACratio = 1.35
System_losses = 5
FederalIncentive= 30

```


```{r}
# test scenario post
test <- "https://reopt.nrel.gov/tool/results/f4e6c9db-3c22-43a4-b2bf-15146aec9896"

```

