---
title: "reOpt Data"
author: "Grace Bianchi"
date: "2023-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(googlesheets4)
library(ggplot2)
```


```{r}
# read in data
reopt_data <- read_sheet("https://docs.google.com/spreadsheets/d/1VROhOTWY4jSeI_zNgFui4ie6QiIz7uzzli8rF72fAyg/edit#gid=0") %>% 
  clean_names() %>% 
  drop_na()


```


```{r}
energy_production_metric <- reopt_data %>% 
  select(cbsa, city_msa, state, annual_renewable_electricity_percent_of_total) %>% 
  rename(annual_renewable_percent = annual_renewable_electricity_percent_of_total) %>% 
  # normalize data 
  mutate(normalized_annual_renewable = (annual_renewable_percent - min(annual_renewable_percent))/(max(annual_renewable_percent)-min(annual_renewable_percent))) %>% 
  select(cbsa, city_msa, state, normalized_annual_renewable)
  
climate_impacts_metric <- reopt_data %>% 
  # normalize total co2 
  mutate(normalized_total_co2 = (lifecycle_total_t_co2 - min(lifecycle_total_t_co2)) / (max(lifecycle_total_t_co2) - min(lifecycle_total_t_co2))) %>% 
  # invert co2
  mutate(inverted_n_total_co2 = 1 - normalized_total_co2) %>% 
  select(cbsa, inverted_n_total_co2)
  
financial_metric <- reopt_data %>% 
  # normalize IRR
  mutate(normalized_irr = (irr - min(irr)) / (max(irr) - min(irr))) %>% 
  select(cbsa, normalized_irr) 

health_impact_metric <- reopt_data  %>% 
  rename(health_emissions_cost = lifecycle_costs_of_health_emissions_difference_from_bau) %>% 
  mutate(normalized_health_emission_cost = (health_emissions_cost - min(health_emissions_cost)) / (max(health_emissions_cost) - min(health_emissions_cost))) %>% 
  # invert 
  mutate(inverted_n_health_emissions_cost = 1 - normalized_health_emission_cost) %>% 
   select(cbsa, inverted_n_health_emissions_cost) 
```


```{r}
# reopt normalized metrics
reopt_metrics_normalized <- energy_production_metric %>% 
  left_join(climate_impacts_metric) %>% 
  left_join(financial_metric) %>% 
  left_join(health_impact_metric)
```

```{r}
sheet_write(reopt_metrics_normalized, ss = "https://docs.google.com/spreadsheets/d/1VROhOTWY4jSeI_zNgFui4ie6QiIz7uzzli8rF72fAyg/edit#gid=498103540", sheet = "normalized_reopt_metrics")
```


```{r}
# mean ("mean_metric"), 95th percentile ("perc_metric"), and distribution for sensitivity analysis

#energy production 
mean_energy_production <- mean(energy_production_metric$normalized_annual_renewable)
mean_energy_production

perc_energy_production <- quantile(energy_production_metric$normalized_annual_renewable, probs = 0.95)
perc_energy_production

energy_distribution <- density(energy_production_metric$normalized_annual_renewable)
plot(energy_distribution)


#climate impacts
mean_total_co2 <- mean(climate_impacts_metric$inverted_n_total_co2)
mean_total_co2

perc_total_co2 <- quantile(climate_impacts_metric$inverted_n_total_co2, probs = 0.95)
perc_total_co2

climate_impacts_distribution <- density(climate_impacts_metric$inverted_n_total_co2)
plot(climate_impacts_distribution)

#financial
mean_irr <- mean(financial_metric$normalized_irr)
mean_irr

perc_irr <- quantile(financial_metric$normalized_irr, probs = 0.95)
perc_irr

irr_distribution <- density(financial_metric$normalized_irr)
plot(irr_distribution)

#health impacts
mean_health_emissions <- mean(health_impact_metric$inverted_n_health_emissions_cost)
mean_health_emissions

perc_health <- quantile(health_impact_metric$inverted_n_health_emissions_cost, probs = 0.95)
perc_health

health_distribution <- density(health_impact_metric$inverted_n_health_emissions_cost)
plot(health_distribution)
```

